apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: "e3784359-740e-40ae-9344-3f436cb0eaff"