apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: "90190fc1-28f7-434a-a1e2-cfd0fbda29ac"