apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: Backend-cluster-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      identityId: ""
      serviceAccountRef:
        name: external-secrets-operator
        namespace: external-secrets
      vaultUrl: ""