apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Backend-clustersecretstore.yaml
- tileserver-clustersecretstore.yaml
- Organisation-clustersecretstore.yaml
- service-account.yaml