apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: ""
    azure.workload.identity/tenant-id: eb7d6aa9-9d91-4abb-a4bb-b23088fe6071