apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: acrsecret
spec:
  externalSecretName: acrsecret
  namespaceSelector: {}
  externalSecretSpec:
    refreshInterval: 10s
    secretStoreRef:
      kind: ClusterSecretStore
      name: disastertech-cluster-store
    target:
      name: acrsecret
      creationPolicy: Owner
      template:
        type: kubernetes.io/dockerconfigjson
        engineVersion: v2
    data:
      - secretKey: .dockerconfigjson
        remoteRef:
          key: acrsecret
