apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: Backend-secrets
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: Backend-cluster-store

  target:
    name: Backend-secrets
    creationPolicy: Owner

  dataFrom:
    - find:
        name:
          regexp: ".*"
      rewrite:
      - regexp:
          source: "(-)"
          target: "_"