apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tileserver-secrets
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: tileserver-cluster-store
  target:
    name: tileserver-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: "(-)"
            target: "_"