apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: Backend-cluster-store
spec:
  provider:
    azurekv:
      identityId: "4736a960-1df3-42df-ad11-87f829e7130c"
      vaultUrl: "https://Backendkeyvault-dev.vault.azure.net/"