apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: "4736a960-1df3-42df-ad11-87f829e7130c"