apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: tileserver-cluster-store
spec:
  provider:
    azurekv:
      identityId: "4736a960-1df3-42df-ad11-87f829e7130c"
      vaultUrl: "https://tileserverkeyvault-dev.vault.azure.net/"