apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-ingress-deployment.yaml
  - service-loadbalancer.yaml
  - nginx-config.yaml
  - rbac.yaml
  - ingress-class.yaml
  - ns-and-sa.yaml
  - crds