apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../argocd/bases

patches:
- path: Application.yaml
- patch: |-
    [
      {
        "op": "replace",
        "path": "/spec/rules/0/host",
        "value": "argocd-prod.disastertech.co"
      },
      {
        "op": "replace",
        "path": "/spec/tls/0/hosts/0",
        "value": "argocd-prod.disastertech.co"
      }
    ]
  target:
    group: networking.k8s.io
    kind: Ingress
    name: argocd-ingress
    version: v1