apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: Application
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: Application-test2
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "172.203.139.141"