apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases
patches:
- path: Backend-clustersecretstore.yaml
- path: tileserver-clustersecretstore.yaml
- path: disastertech-clustersecretstore.yaml
- path: service-account.yaml