apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: "ee6e1ec6-8731-43d1-9811-f99b5a2d9da1"