apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: Application
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: Application-qa
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "20.185.70.194"